services:
  - type: web
    name: clipverb
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist

    envVars:
      - key: VITE_GEMINI_API_KEY
        value: "AIzaSyDE8YVW_M6vGRyqkA6qaq1PyDLiObuWg8s"
