services:
  - type: static
    name: clipverb
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: API_KEY
        sync: false # Tells Render not to sync this to other services for security